import { app, BrowserWindow, ipcMain, nativeTheme } from 'electron';
import * as FileSystem from './main/fileSystem';
import type { Assignment, Member } from './shared/types';
import { runSimulatedAnnealing } from './algorithm/simulatedAnnealing';
import { updateEdgeWeights } from './algorithm/edgeWeights';

// Mock API: Generate fake member data (Replace with real API later)
function generateMockMembers(): Member[] {
  const departments = ['개발팀', '디자인팀', '마케팅팀', '영업팀', 'HR팀', '경영지원팀'];
  const lastNames = ['김', '이', '박', '최', '정', '강', '조', '윤', '장', '임'];
  const firstNames = [
    '민준',
    '서연',
    '예준',
    '지우',
    '도윤',
    '서준',
    '하은',
    '주원',
    '지호',
    '수아',
  ];

  return Array.from({ length: 100 }, (_, i) => ({
    id: i + 1,
    realName: `${lastNames[i % lastNames.length]}${firstNames[i % firstNames.length]}${Math.floor(i / 10) || ''}`,
    nickname: `nick${i + 1}`,
    department: departments[i % departments.length],
  }));
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// ============================================================================
// IPC Handlers
// ============================================================================

// Member operations
ipcMain.handle('fetch-members', async () => {
  // TODO: Replace with real eHR API call using apiToken from settings
  console.log('Fetching members (mocked)...');
  return generateMockMembers();
});

// Assignment operations
ipcMain.handle('load-assignments', async () => {
  return await FileSystem.loadAssignments();
});

ipcMain.handle('load-assignment', async (_event, timestamp: number) => {
  return await FileSystem.loadAssignment(timestamp);
});

ipcMain.handle('delete-assignment', async (_event, timestamp: number) => {
  await FileSystem.deleteAssignment(timestamp);
});

ipcMain.handle('create-assignment', async (_event, memberIds: number[]) => {
  console.log(`Creating assignment for ${memberIds.length} members...`);

  // Load current edge weights
  const currentWeights = await FileSystem.loadEdgeWeights();

  // Run Simulated Annealing to find optimal groups
  const result = runSimulatedAnnealing(memberIds, currentWeights);

  const timestamp = Date.now();
  const assignment: Assignment = {
    timestamp,
    groups: result.groups,
    participatingMembers: memberIds,
  };

  // Update edge weights based on the new assignment
  const { updated: updatedWeights, updates: edgeUpdates } = updateEdgeWeights(
    currentWeights,
    result.groups
  );

  // Save updated weights
  await FileSystem.saveEdgeWeights(updatedWeights);

  // Save assignment
  await FileSystem.saveAssignment(assignment, edgeUpdates);

  console.log(`Assignment created with cost ${result.cost}, ${result.groups.length} groups`);

  return assignment;
});

// Settings operations
ipcMain.handle('load-settings', async () => {
  return await FileSystem.loadSettings();
});

ipcMain.handle(
  'save-settings',
  async (_event, settings: Partial<import('./shared/types').Settings>) => {
    await FileSystem.updateSettings(settings);
  }
);

// Edge weights operations
ipcMain.handle('load-edge-weights', async () => {
  return await FileSystem.loadEdgeWeights();
});

ipcMain.handle(
  'save-edge-weights',
  async (_event, weights: import('./shared/types').EdgeWeightMap) => {
    await FileSystem.saveEdgeWeights(weights);
  }
);

// Theme operations
ipcMain.handle('get-system-theme', () => {
  return nativeTheme.shouldUseDarkColors ? 'dark' : 'light';
});

nativeTheme.on('updated', () => {
  const theme = nativeTheme.shouldUseDarkColors ? 'dark' : 'light';
  mainWindow?.webContents.send('system-theme-changed', theme);
});
